In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\Sai Kumar\Documents\pandas\loan_risk_prediction_dataset.csv")

In [3]:
df

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1
3,32,56307.0,11531.0,549.0,11,Male,NaN,New York,Unemployed,0
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0
...,...,...,...,...,...,...,...,...,...,...
4995,24,36780.0,23383.0,NaN,23,Male,Masters,Houston,Salaried,0
4996,66,99146.0,9760.0,306.0,14,Male,PhD,New York,Unemployed,0
4997,26,58100.0,18230.0,311.0,10,Female,High School,San Francisco,Self-Employed,0
4998,53,58513.0,12373.0,813.0,23,Male,PhD,Houston,Salaried,1
4999,36,58928.0,23615.0,648.0,10,Male,NaN,New York,Self-Employed,1

In [4]:
# to see all columns
pd.set_option("display.max_columns",10)

In [5]:
# to see overview of dataset
df.shape

(5000, 10)

In [6]:
# to see columns
df.columns

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'YearsExperience',
       'Gender', 'Education', 'City', 'EmploymentType', 'LoanApproved'],
      dtype='str')

In [7]:
# to see overview of a dataset quickly
df.describe()

,Age,Income,LoanAmount,CreditScore,YearsExperience,LoanApproved
count,5000.000000,4804.000000,5000.000000,4806.000000,5000.000000,5000.000000
mean,43.584600,49738.123022,19870.768600,575.494590,19.599000,0.230200
std,14.919094,15101.361851,8046.542413,160.550839,11.516837,0.421003
min,18.000000,-3731.000000,-10059.000000,300.000000,0.000000,0.000000
25%,31.000000,39608.500000,14455.250000,433.000000,10.000000,0.000000
50%,43.000000,49488.000000,19842.500000,579.000000,20.000000,0.000000
75%,56.000000,59917.000000,25326.750000,712.000000,29.000000,0.000000
max,69.000000,99146.000000,48353.000000,849.000000,39.000000,1.000000

In [8]:
# Now see missing values in each column
df.isna().sum()

Age                  0
Income             196
LoanAmount           0
CreditScore        194
YearsExperience      0
Gender               0
Education          198
City                 0
EmploymentType       0
LoanApproved         0
dtype: int64

In [9]:
df.isna().sum()*100/len(df)

Age                0.00
Income             3.92
LoanAmount         0.00
CreditScore        3.88
YearsExperience    0.00
Gender             0.00
Education          3.96
City               0.00
EmploymentType     0.00
LoanApproved       0.00
dtype: float64

In [10]:
df.dtypes

Age                  int64
Income             float64
LoanAmount         float64
CreditScore        float64
YearsExperience      int64
Gender                 str
Education              str
City                   str
EmploymentType         str
LoanApproved         int64
dtype: object

In [11]:
df.tail()

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
4995,24,36780.0,23383.0,NaN,23,Male,Masters,Houston,Salaried,0
4996,66,99146.0,9760.0,306.0,14,Male,PhD,New York,Unemployed,0
4997,26,58100.0,18230.0,311.0,10,Female,High School,San Francisco,Self-Employed,0
4998,53,58513.0,12373.0,813.0,23,Male,PhD,Houston,Salaried,1
4999,36,58928.0,23615.0,648.0,10,Male,NaN,New York,Self-Employed,1

In [12]:
df.isna().sum()

Age                  0
Income             196
LoanAmount           0
CreditScore        194
YearsExperience      0
Gender               0
Education          198
City                 0
EmploymentType       0
LoanApproved         0
dtype: int64

# Handle neagative values.

In [13]:
# we have negative values Income and LoanAmount...
df[df["Income"]<0]

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
2939,65,-3731.0,10651.0,729.0,22,Male,Masters,San Francisco,Salaried,0
3263,23,-3083.0,16964.0,331.0,12,Male,PhD,New York,Salaried,0
4523,35,-213.0,14048.0,582.0,30,Female,Bachelors,Chicago,Self-Employed,0

In [14]:
# Convert all the - values into NAN...
df.loc[df["Income"]<0,"Income"]=np.nan

In [15]:
df.isna().sum()

Age                  0
Income             199
LoanAmount           0
CreditScore        194
YearsExperience      0
Gender               0
Education          198
City                 0
EmploymentType       0
LoanApproved         0
dtype: int64

In [16]:
# we have nan values in Income has all 199 values...so replace with them medain by Education Type
# df["Income"]=df.groupby["EmploymentType"]("Income").transform(lambda x:x.fillna(x.median())
df["Income"] = df.groupby("EmploymentType")["Income"].transform(
    lambda x: x.fillna(x.median()))

In [17]:
#df[df["CreditScore"] < 300]
df[df["CreditScore"] > 850]
#df["CreditScore"].min()
#df["CreditScore"].max()

Empty DataFrame
Columns: [Age, Income, LoanAmount, CreditScore, YearsExperience, Gender, Education, City, EmploymentType, LoanApproved]
Index: []

In [18]:
df[df["CreditScore"].isna()]

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
13,53,48699.0,20554.0,NaN,22,Female,NaN,Chicago,Self-Employed,0
109,41,58998.0,20489.0,NaN,27,Female,Masters,Chicago,Unemployed,0
144,18,33554.0,21667.0,NaN,6,Female,Masters,Houston,Salaried,0
151,32,47197.0,27933.0,NaN,13,Male,High School,Chicago,Salaried,0
173,49,27936.0,1138.0,NaN,35,Male,Masters,Chicago,Unemployed,0
...,...,...,...,...,...,...,...,...,...,...
4898,31,29171.0,14203.0,NaN,16,Male,PhD,San Francisco,Unemployed,0
4906,27,32790.0,13801.0,NaN,11,Female,PhD,Houston,Unemployed,0
4950,61,43815.0,16709.0,NaN,7,Male,Bachelors,Chicago,Self-Employed,0
4993,62,68099.0,25124.0,NaN,35,Male,Bachelors,Houston,Unemployed,0
4995,24,36780.0,23383.0,NaN,23,Male,Masters,Houston,Salaried,0

In [19]:
df["CreditScore"]=df["CreditScore"].fillna(df["CreditScore"].median())

In [20]:
df["CreditScore"].median()

np.float64(579.0)

# # We have missing values in income,creditscore,education..Let's handle them

In [21]:
df.isna().sum()

Age                  0
Income               0
LoanAmount           0
CreditScore          0
YearsExperience      0
Gender               0
Education          198
City                 0
EmploymentType       0
LoanApproved         0
dtype: int64

In [22]:
# Now we have education has NULL values..
df["Education"]=df["Education"].fillna("unknown")

In [23]:
df.isna().sum()

Age                0
Income             0
LoanAmount         0
CreditScore        0
YearsExperience    0
Gender             0
Education          0
City               0
EmploymentType     0
LoanApproved       0
dtype: int64

In [24]:
df.shape

(5000, 10)

In [25]:
# Now we hanlded all null values...

In [26]:
df.describe()

,Age,Income,LoanAmount,CreditScore,YearsExperience,LoanApproved
count,5000.000000,5000.00000,5000.000000,5000.00000,5000.000000,5000.000000
mean,43.584600,49760.33920,19870.768600,575.63060,19.599000,0.230200
std,14.919094,14747.27979,8046.542413,157.40616,11.516837,0.421003
min,18.000000,129.00000,-10059.000000,300.00000,0.000000,0.000000
25%,31.000000,40036.00000,14455.250000,440.00000,10.000000,0.000000
50%,43.000000,49535.50000,19842.500000,579.00000,20.000000,0.000000
75%,56.000000,59447.00000,25326.750000,706.00000,29.000000,0.000000
max,69.000000,99146.00000,48353.000000,849.00000,39.000000,1.000000

# Exploratory Data Analysis (EDA)

In [27]:
# Check Approval Rate
df.columns

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'YearsExperience',
       'Gender', 'Education', 'City', 'EmploymentType', 'LoanApproved'],
      dtype='str')

In [28]:
# Check Approval Rate
df["LoanApproved"].mean()*100

np.float64(23.02)

In [29]:
# Compare Approved vs Rejected Customers
df.groupby("LoanApproved")["CreditScore"].min()

LoanApproved
0    300.0
1    300.0
Name: CreditScore, dtype: float64

In [30]:
df

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1
3,32,56307.0,11531.0,549.0,11,Male,unknown,New York,Unemployed,0
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0
...,...,...,...,...,...,...,...,...,...,...
4995,24,36780.0,23383.0,579.0,23,Male,Masters,Houston,Salaried,0
4996,66,99146.0,9760.0,306.0,14,Male,PhD,New York,Unemployed,0
4997,26,58100.0,18230.0,311.0,10,Female,High School,San Francisco,Self-Employed,0
4998,53,58513.0,12373.0,813.0,23,Male,PhD,Houston,Salaried,1
4999,36,58928.0,23615.0,648.0,10,Male,unknown,New York,Self-Employed,1

In [31]:
df["LoanApproved"]=df["LoanApproved"].astype("str")

In [32]:
df.dtypes

Age                  int64
Income             float64
LoanAmount         float64
CreditScore        float64
YearsExperience      int64
Gender                 str
Education              str
City                   str
EmploymentType         str
LoanApproved           str
dtype: object

In [33]:
df["LoanApproved"]=df["LoanApproved"].str.replace("1","Yes")

In [34]:
df["LoanApproved"]=df["LoanApproved"].str.replace("0","No")

In [35]:
# credit_score vs approval
# 👉 Do approved customers have higher credit score?  =YEs
df.groupby("LoanApproved")["CreditScore"].mean()

LoanApproved
No     535.954014
Yes    708.311034
Name: CreditScore, dtype: float64

In [36]:
# Loan Amount vs Approval
df.groupby("LoanApproved")["LoanAmount"].min()

LoanApproved
No    -10059.0
Yes    -4933.0
Name: LoanAmount, dtype: float64

In [37]:
df[df["LoanAmount"]<0]
#df.dtypes

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
17,39,35401.0,-4250.0,615.0,32,Female,PhD,Chicago,Unemployed,No
93,41,73864.0,-5728.0,525.0,22,Male,High School,Chicago,Unemployed,No
439,68,32242.0,-2711.0,579.0,24,Male,High School,Chicago,Unemployed,No
512,46,49172.0,-1595.0,803.0,35,Male,High School,New York,Unemployed,No
609,52,39402.0,-2533.0,385.0,21,Female,High School,New York,Self-Employed,No
743,28,45116.0,-2361.0,579.0,29,Male,PhD,Chicago,Self-Employed,No
818,30,52945.0,-4933.0,849.0,22,Male,PhD,San Francisco,Self-Employed,Yes
1054,47,38160.0,-805.0,755.0,8,Female,Bachelors,New York,Salaried,No
1119,37,86623.0,-2314.0,476.0,29,Male,PhD,Chicago,Self-Employed,No
1280,48,29476.0,-3382.0,358.0,16,Female,Bachelors,Houston,Unemployed,No
1494,51,36738.0,-5131.0,666.0,37,Male,High School,New York,Self-Employed,No
1599,33,26289.0,-2581.0,592.0,36,Male,High School,Chicago,Salaried,No
1678,61,36330.0,-2431.0,518.0,26,Female,PhD,Chicago,Salaried,No
1681,59,61554.0,-1752.0,753.0,14,Male,Bachelors,Houston,Unemployed,No
1832,41,16081.0,-1233.0,501.0,18,Male,PhD,Chicago,Self-Employed,No
1950,69,56384.0,-1126.0,755.0,38,Male,Masters,Houston,Unemployed,No
2195,40,84109.0,-3223.0,542.0,8,Male,High School,Chicago,Unemployed,No
2322,27,79983.0,-4141.0,511.0,6,Male,Bachelors,Chicago,Salaried,No
3299,39,62774.0,-801.0,395.0,20,Female,Bachelors,Chicago,Unemployed,No
3354,69,41202.0,-7634.0,424.0,37,Male,Bachelors,Chicago,Unemployed,No
3574,36,57479.0,-220.0,727.0,3,Female,Masters,New York,Self-Employed,Yes
3685,35,53420.0,-4785.0,658.0,7,Male,PhD,Chicago,Salaried,Yes
3969,52,75913.0,-1445.0,574.0,34,Male,Bachelors,Houston,Self-Employed,No
3993,44,70360.0,-754.0,813.0,1,Female,Bachelors,San Francisco,Unemployed,No
4187,21,24497.0,-10059.0,823.0,14,Female,Bachelors,Chicago,Self-Employed,No
4464,67,60541.0,-309.0,827.0,21,Female,High School,Houston,Unemployed,No
4498,61,33831.0,-1341.0,825.0,12,Male,Masters,Chicago,Unemployed,No
4552,56,65149.0,-456.0,693.0,15,Female,Bachelors,Houston,Salaried,Yes

In [38]:
df["LoanAmount"].min()

np.float64(-10059.0)

In [39]:
df.loc[df["LoanAmount"]<0,"LoanAmount"]=np.nan

In [40]:
df[df["LoanAmount"]<0]

Empty DataFrame
Columns: [Age, Income, LoanAmount, CreditScore, YearsExperience, Gender, Education, City, EmploymentType, LoanApproved]
Index: []

In [41]:
df["LoanAmount"]

0       31258.0
1       23262.0
2       26530.0
3       11531.0
4       27871.0
         ...
4995    23383.0
4996     9760.0
4997    18230.0
4998    12373.0
4999    23615.0
Name: LoanAmount, Length: 5000, dtype: float64

In [42]:
df.groupby("LoanApproved")["Income"].mean()

LoanApproved
No     48256.998571
Yes    54787.583406
Name: Income, dtype: float64

In [43]:
df.groupby("LoanApproved")["LoanAmount"].max()

LoanApproved
No     45197.0
Yes    48353.0
Name: LoanAmount, dtype: float64

In [44]:
df.groupby("LoanApproved")["LoanAmount"].mean()

LoanApproved
No     19932.624575
Yes    20219.344377
Name: LoanAmount, dtype: float64

In [45]:
df["LoanAmount"].min()

np.float64(4.0)

In [46]:
df["LoanAmount"].max()

np.float64(48353.0)

In [74]:
df["loan_income_Ratio"] = df["loanamount"] / df["income"]

In [48]:
df.groupby("LoanApproved")["Loan_Income_Ratio"].mean()*100

LoanApproved
No     52.643151
Yes    38.829331
Name: Loan_Income_Ratio, dtype: float64

# Categorical Analysis

In [49]:
df["LoanApproved"]=df["LoanApproved"].str.replace("Yes","1")
df["LoanApproved"]=df["LoanApproved"].str.replace("No","0")
df["LoanApproved"]=df["LoanApproved"].astype(int)
df.dtypes

Age                    int64
Income               float64
LoanAmount           float64
CreditScore          float64
YearsExperience        int64
Gender                   str
Education                str
City                     str
EmploymentType           str
LoanApproved           int64
Loan_Income_Ratio    float64
dtype: object

In [50]:
df.groupby("Education")["LoanApproved"].mean()*100

Education
Bachelors      21.557377
High School    22.025316
Masters        23.288815
PhD            25.104254
unknown        23.737374
Name: LoanApproved, dtype: float64

In [51]:
df.groupby("EmploymentType")["LoanApproved"].mean()*100
#df.dtypes

EmploymentType
Salaried         33.291925
Self-Employed    32.543353
Unemployed        3.132530
Name: LoanApproved, dtype: float64

In [52]:
df.groupby("City")["LoanApproved"].mean().sort_values(ascending=False)*100

City
San Francisco    23.866348
Chicago          23.312883
New York         23.032312
Houston          21.834416
Name: LoanApproved, dtype: float64

In [56]:
engine=create_engine("postgresql://postgres:7583@localhost:5432/customer_loans")

NameError: name 'create_engine' is not defined

In [ ]:
pip install psycopg2 sqlalchemy

In [98]:
from sqlalchemy import create_engine
engine=create_engine("postgresql://postgres:7583@localhost:5432/customer_loans")

In [60]:
df.to_sql(name="loans",
          con=engine,
          if_exists="replace",
          index=False)

1000

In [ ]:
df.shape

In [54]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [61]:
df.to_sql(name="loans",
          con=engine,
          if_exists="replace",
          index=False)

1000

In [57]:
from sqlalchemy import create_engine

In [62]:
df

,age,income,loanamount,creditscore,yearsexperience,...,education,city,employmenttype,loanapproved,loan_income_ratio
0,56,48353.0,31258.0,675.0,20,...,High School,Houston,Unemployed,0,0.646454
1,69,57462.0,23262.0,586.0,6,...,High School,San Francisco,Self-Employed,0,0.404824
2,46,44219.0,26530.0,781.0,26,...,PhD,Houston,Self-Employed,1,0.599968
3,32,56307.0,11531.0,549.0,11,...,unknown,New York,Unemployed,0,0.204788
4,60,37034.0,27871.0,500.0,19,...,High School,Chicago,Unemployed,0,0.752579
...,...,...,...,...,...,...,...,...,...,...,...
4995,24,36780.0,23383.0,579.0,23,...,Masters,Houston,Salaried,0,0.635753
4996,66,99146.0,9760.0,306.0,14,...,PhD,New York,Unemployed,0,0.098441
4997,26,58100.0,18230.0,311.0,10,...,High School,San Francisco,Self-Employed,0,0.313769
4998,53,58513.0,12373.0,813.0,23,...,PhD,Houston,Salaried,1,0.211457
4999,36,58928.0,23615.0,648.0,10,...,unknown,New York,Self-Employed,1,0.400743

In [63]:
df.isna().sum()

age                   0
income                0
loanamount           28
creditscore           0
yearsexperience       0
gender                0
education             0
city                  0
employmenttype        0
loanapproved          0
loan_income_ratio    28
dtype: int64

In [65]:
df[df["loanamount"]<0]

Empty DataFrame
Columns: [age, income, loanamount, creditscore, yearsexperience, gender, education, city, employmenttype, loanapproved, loan_income_ratio]
Index: []

[0 rows x 11 columns]

In [71]:
df["loanamount"]=df["loanamount"].fillna(df["loanamount"].median(), inplace=True)

C:\Users\Sai Kumar\AppData\Local\Temp\ipykernel_36628\1270025542.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["loanamount"]=df["loanamount"].fillna(df["loanamount"].median(), inplace=True)

In [76]:
df.isna().sum()

age                   0
income                0
loanamount            0
creditscore           0
yearsexperience       0
gender                0
education             0
city                  0
employmenttype        0
loanapproved          0
loan_income_ratio    28
loan_income_Ratio     0
dtype: int64

In [92]:
df["loan_income_ratio"] = df["loanamount"] / df["income"]

In [93]:
df.isna().sum()

age                  0
income               0
loanamount           0
creditscore          0
yearsexperience      0
gender               0
education            0
city                 0
employmenttype       0
loanapproved         0
loan_income_ratio    0
dtype: int64

In [94]:
df[df["loan_income_ratio"].isna()]

Empty DataFrame
Columns: [age, income, loanamount, creditscore, yearsexperience, gender, education, city, employmenttype, loanapproved, loan_income_ratio]
Index: []

[0 rows x 11 columns]

In [91]:
# df=df.drop(columns="loan_income_Ratio")

In [96]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, income, loanamount, creditscore, yearsexperience, gender, education, city, employmenttype, loanapproved, loan_income_ratio]
Index: []

[0 rows x 11 columns]

In [97]:
df.isna().sum()

age                  0
income               0
loanamount           0
creditscore          0
yearsexperience      0
gender               0
education            0
city                 0
employmenttype       0
loanapproved         0
loan_income_ratio    0
dtype: int64

In [99]:
df.to_sql(name="customer_loans_approval",
          con=engine,
          if_exists="replace",
          index=False)

1000